version: '3'

services:
  db_service:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: chain_stores
    volumes:
      - ./mongo:/data/db